- name: Announce Controller
  hosts: all
  remote_user: controller
  vars:
    controller_root: "/controller"
  tasks:

  - name: Create keyring and public keys
    command: yarn run init
    args:
      chdir: "{{ controller_root }}/restroom"

  - name: Setup information in redis
    uri:
      url: "https://{{domain_name}}/api/did-setup.chain"
    delegate_to: localhost

  - name: Create Controller DID document
    uri:
      url: "https://{{domain_name}}/api/did-controller.chain"
    failed_when: false
    register: response
    delegate_to: localhost

  - debug:
      msg: "{{ response.json }}"
    failed_when: response.status == 500

  - name: Download the public keys
    fetch:
      src: "{{ controller_root }}/contracts/public_keys.json"
      dest: "publickeys/{{ inventory_hostname }}.json"
      flat: yes
