- name: create specs
  set_fact:
    specs_name:
      signer_did_spec: "{{ 'sandbox.' + context_name + '_A' }}"
      did_spec: "{{ 'sandbox.' + context_name }}"

- name: create keys
  set_fact:
    create_request: "{{ context_keyring |
      combine(context_header, specs_name) }}"
    deactivate_request: "{{ context_keyring |
      combine(specs_name) }}"

- name: Create working dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - "{{ context_root }}/contracts/{{ context_name }}"

- name: Copy contracts (permissions may be wrong)
  synchronize:
    src: "contracts/"
    dest: "{{ context_root }}/contracts/{{ context_name }}"
    owner: no
    group: no

- name: Copy chain files
  template:
    src: "contracts/{{ item }}.j2"
    dest: "{{ context_root }}/contracts/{{ context_name }}/{{ item }}"
  with_items:
    - "create_sandbox_did.yml"
    - "deactivate_sandbox_did.yml"

- name: Create keys
  copy: content="{{ create_request }}" dest={{ context_root }}/contracts/{{ context_name }}/1_create_request.keys

- name: Create keys
  copy: content="{{ deactivate_request }}" dest={{ context_root }}/contracts/{{ context_name }}/1_deactivate_request.keys
