- name: Create working dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - "{{ context_root }}/contracts/{{ context_name }}"

- name: Copy contracts (permissions may be wrong)
  synchronize:
    src: "contracts/"
    dest: "{{ context_root }}/contracts/{{ context_name }}"
    owner: no
    group: no
