---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Create working dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: controller
    group: controller
  with_items:
    - "{{ context_root }}"
    - "{{ context_root }}/contracts"

- name: Copy app
  become: true
  copy:
    src: "Dockerfile"
    dest: "{{ context_root }}/"
