---
# TODO: sometime online .bashrc contains an instruction that
# doesn't do anything if login is not interactive
- name: Populate PATH
  become: true
  setup:

- name: Install yarn
  become: true
  community.general.npm:
    name: yarn
    global: yes
    state: latest

- name: Install pm2
  become: true
  community.general.npm:
    name: pm2
    global: yes
    state: latest

- name: Update packages of restroom
  become: true
  community.general.yarn:
    path: "{{ context_root }}/restroom"
    state: latest

- name: start and save controller with pm2
  become: true
  shell: pm2 delete ecosystem.config.js && pm2 start ecosystem.config.js && pm2 save
  args:
    chdir: "{{ controller_root }}/restroom"

- name: start at system start
  command: pm2 startup -u controller --hp /home/controller
  environment:
    PATH: "{{ ansible_env.PATH }}"
