---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Install package dependencies
  ansible.builtin.package:
    name:
      - nginx
      - curl
      - rsync
      - jq
      - parallel
    state: latest

- name: Install zenroom
  ansible.builtin.get_url:
    url: https://files.dyne.org/zenroom/nightly/zenroom-linux-amd64
    dest: /usr/local/bin/zenroom
    mode: a+x

- name: Create working dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: controller
    group: controller
  with_items:
    - "{{ controller_root }}"
    - "{{ controller_root }}/restroom"
    - "{{ controller_root }}/scripts"
    - "{{ data_dir }}"
    - "{{ logs_dir }}"

- name: Copy app
  become: true
  copy:
    src: "../restroom/{{ item }}"
    dest: "{{ controller_root }}/restroom/"
  with_items:
    - restroom.mjs
    - init.mjs
    - package.json
    - yarn.lock

- name: Copy script
  become: true
  copy:
    src: "../scripts/{{ item }}"
    dest: "{{ controller_root }}/scripts/"
    mode: a+x
    owner: controller
    group: controller
  with_items:
    - "scrub.sh"
    - "git_push.sh"

# - name: Config restroom in private network
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     line: 127.0.0.1 {{ domain_name }}
#     owner: root
#     group: root
#     mode: '0644'

- name: Create .env
  become: true
  blockinfile:
    path: "{{ controller_root }}/restroom/.env"
    create: true
    block: |
      FILES_DIR={{ data_dir }}
      ZENCODE_DIR=../api
      INIT_ZENCODE_DIR=../blockchains_client
      LOGGER_DIR=/var/log/controller/
      USE_TIMESTAMP=y
      USE_FILES=y
      USE_ETHEREUM=y
      USE_PLANETMINT=y
      USE_GIT=y
      USE_LOGGER=y
      USE_HTTP=y
      HOST={{ domain_name }}
      HTTP_PORT=80
      HTTPS_PORT=443
      LOCAL_PORT={{ local_port }}
      CHAIN_EXT=chain
      YML_EXT=yml

- lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ domain_name }}"
    insertafter: "127.0.0.1"
    state: present

- name: Copy contracts (permissions may be wrong)
  become: true
  synchronize:
    src: "../api"
    dest: "{{ controller_root }}"
    owner: no
    group: no

- name: Fix contracts permissions
  file:
    dest: "{{ controller_root }}/api"
    owner: controller
    group: controller
    recurse: yes

- name: Copy init contracts (permissions may be wrong)
  become: true
  synchronize:
    src: "../client/v1/blockchains_client"
    dest: "{{ controller_root }}"
    owner: no
    group: no

- name: Fix init contracts permissions
  file:
    dest: "{{ controller_root }}/blockchains_client"
    owner: controller
    group: controller
    recurse: yes

- name: Copy secrets
  become: true
  synchronize:
    src: "../secrets"
    dest: "{{ controller_root }}"
    owner: no
    group: no

- name: Fix secrets permissions
  file:
    dest: "{{ controller_root }}/secrets"
    owner: controller
    group: controller
    recurse: yes

- name: Clone or pull data dir
  become: true
  shell: |
    REPOSRC=git@github.com:dyne/W3C-DID-data.git
    LOCALREPO="{{ data_dir }}/data"

    LOCALREPO_VC_DIR=$LOCALREPO/.git

    if [ ! -d $LOCALREPO_VC_DIR ]
    then
        git clone $REPOSRC $LOCALREPO
    else
        cd $LOCALREPO
        git pull --rebase origin main
    fi

- name: Download pm2 ecosystem
  become: true
  get_url:
    url: "https://raw.githubusercontent.com/dyne/W3C-DID/main/restroom/ecosystem.config.js"
    dest: "{{ controller_root }}/restroom/"
    force: true

- name: Remove default config
  file:
    state: absent
    dest: /etc/nginx/sites-enabled/default

- name: Config for nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf force=true

- name: Restart nginx
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: nginx

- name: Ensure that one day controller push to github
  become: true
  ansible.builtin.cron:
    name: "git push dids"
    minute: "0"
    hour: "*"
    job: "cd {{ controller_root }}; log=\"{{ logs_dir }}/push.log\" ./scripts/git_push.sh {{ data_dir }}/data; cd $OLDPWD"
