---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Install package dependencies
  ansible.builtin.package:
    name:
      - nginx
      - curl
      - rsync
      - jq
    state: latest

- name: Create working dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: controller
    group: controller
  with_items:
    - "{{ controller_root }}"
    - "{{ controller_root }}/restroom"
    - "{{ data_dir }}"

- name: Copy app
  become: true
  copy:
    src: "../restroom/{{ item }}"
    dest: "{{ controller_root }}/restroom/"
  with_items:
    - restroom.mjs
    - package.json
    - yarn.lock

# - name: Config restroom in private network
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     line: 127.0.0.1 {{ domain_name }}
#     owner: root
#     group: root
#     mode: '0644'

- name: Create .env
  become: true
  blockinfile:
    path: "{{ controller_root }}/restroom/.env"
    create: true
    block: |
      FILES_DIR={{ data_dir }}
      ZENCODE_DIR=../api
      USE_TIMESTAMP=y
      USE_FILES=y
      USE_ETHEREUM=y
      USE_PLANETMINT=y
      USE_HTTP=y
      HOST=127.0.0.1
      HTTP_PORT={{ local_port }}
      CHAIN_EXT=chain
      YML_EXT=yml

- name: Copy contracts (permissions may be wrong)
  become: true
  synchronize:
    src: "../api"
    dest: "{{ controller_root }}"
    owner: no
    group: no

- name: Fix contracts permissions
  file:
    dest: "{{ controller_root }}/api"
    owner: controller
    group: controller
    recurse: yes

- name: Copy private_contracts
  become: true
  synchronize:
    src: "../private_contracts"
    dest: "{{ controller_root }}"
    owner: no
    group: no

- name: Fix private_contracts permissions
  file:
    dest: "{{ controller_root }}/private_contracts"
    owner: controller
    group: controller
    recurse: yes

# TODO: use ssh instead of http
- name: Clone data dir
  become: true
  ansible.builtin.git:
    repo: https://github.com/dyne/W3C-DID-data.git
    dest: "{{ data_dir }}/data"

- name: Download pm2 ecosystem
  become: true
  get_url:
    url: "https://raw.githubusercontent.com/dyne/W3C-DID/main/restroom/ecosystem.config.js"
    dest: "{{ controller_root }}/restroom/"
    force: true

- name: Remove default config
  file:
    state: absent
    dest: /etc/nginx/sites-enabled/default

- name: Config for nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Restart nginx
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
