---
- name: Add the user 'controller'
  ansible.builtin.user:
    name: controller
    shell: /bin/bash
- name: Create .ssh directory
  file:
    path: /home/controller/.ssh
    state: directory
    owner: controller
    group: controller
- name: Set authorized keys for user controller
  copy:
    src: /root/.ssh/authorized_keys
    remote_src: true
    dest: /home/controller/.ssh/authorized_keys
    owner: controller
    group: controller

- name: Remove default .bashrc
  copy:
    src: .bashrc
    dest: /home/controller/.bashrc

- name: Add ssh private key
  copy:
    src: "{{ github_key }}"
    dest: /home/controller/.ssh/{{ github_key }}
    mode: '0600'
    owner: controller
    group: controller

- name: Add ssh config
  template:
    src: sshconfig.j2
    dest: /home/controller/.ssh/config
    mode: '0600'
    owner: controller
    group: controller
